name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

concurrency:
  group: release_workflow
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Apply Google Services Patch
        run: git apply ./scripts/enable-android-google-services.patch
      - name: Remove Emoji Font
        run: |
          rm -rf fonts/NotoEmoji
          yq -i 'del( .flutter.fonts[] | select(.family == "NotoEmoji") )' pubspec.yaml
      - run: flutter pub get
      - name: Prepare Android Release Build
        env:
          FDROID_KEY: ${{ secrets.FDROID_KEY }}
          FDROID_KEY_PASS: ${{ secrets.FDROID_KEY_PASS }}
          PLAYSTORE_DEPLOY_KEY: ${{ secrets.PLAYSTORE_DEPLOY_KEY }}
        run: ./scripts/prepare-android-release.sh
      - run: | 
          # build apk
          COMMIT_HASH=${GITHUB_SHA::8} 
          BUILD_NAME="debug-$COMMIT_HASH"
          flutter build apk --release --build-name=$BUILD_NAME
      # - name: Upload to release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAGES_DEPLOY_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: build/app/outputs/apk/release/app-release.apk
      #     asset_name: fluffychat.apk
      #     asset_content_type: application/vnd.android.package-archive
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1
        with:
          # Artifact name
          name: fluffychat.apk
          # A file, directory or wildcard pattern that describes what to upload
          path: build/app/outputs/apk/release/app-release.apk
